### PR TITLE
Restricted Linter options type

### LINKED ISSUE #1167: Linter should throw if passed a string configuration
#### Repro

I did a silly and forgot to call `JSON.parse` on the value being passed to `Linter`.

```typescript
// wrong
let linter = new Linter("file.ts", "...", "{ \"rules\": ... } ");
```

```typescript
// correct
let linter = new Linter('file.ts", "...", { rules: ... });
```

#### Actual behavior

It ran without error, but reported 0 lint failures.

#### Expected behavior

It should have blown up and told me I'm an idiot for passing an invalid tslint.json equivalent.

:(

*(I'll send a PR for this unless directed otherwise)*

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
Fixes #1167

Wasn't sure where unit tests for this would go, if you do want to test constructor logic.

### CODE REVIEW

**Comment by JKillian** [comment]
👍   We can probably get away without a test here for now, it would break some of the full CLI tests if it didn't accept valid input. Do you think we should also add a check for `== null` and throw an error then?

**Comment by JoshuaKGoldberg** [comment]
Yeah, that sounds like a good thing to add.

Do you consider any option fields mandatory? If so, instead of checking for `typeof` it might make sense to check for their existence.

**Comment by JKillian** [comment]
Strangely enough, it looks like `ILinterOptions.formatter` must be specified, while everything else can be left undefined. This seems more like a bug to me than anything, so let's not worry about it - I think `ILinterOptions.formatter` should be made optional in the long run.

On the other hand, if everything is optional, passing `null` as the current options isn't unreasonable. Maybe we should just modify `computeFullOptions` to handle the case where the whole options object is `null` and to provided a default value for `formatter` if not provided?

**Comment by JoshuaKGoldberg** [comment]
Thoughts on this draft? Is there some source of truth for what `formatter`should default to?

File: src/tslint.ts [hunk 1]
```diff
@@ -99,13 +98,19 @@ class Linter {
...
         }
-        this.options.rulesDirectory = arrayify(rulesDirectory).concat(arrayify(configuration.rulesDirectory));
-        this.options.configuration = configuration;
+
+        let { configuration, formatter, formattersDirectory, rulesDirectory } = options;
+
+        return {
+            configuration: configuration || DEFAULT_CONFIG,
+            formatter: formatter || "json",
+            formattersDirectory: formattersDirectory || "",
```
Comment (JKillian) [inline src/tslint.ts]: let's not add the `|| ""` here, it's fine if this stays `null`. (An empty string would get treated as the current directory which could lead to unexpected behavior)

File: src/tslint.ts [hunk 2]
```diff
@@ -99,13 +98,19 @@ class Linter {
...
+            options = {};
         }
-        this.options.rulesDirectory = arrayify(rulesDirectory).concat(arrayify(configuration.rulesDirectory));
-        this.options.configuration = configuration;
+
+        let { configuration, formatter, formattersDirectory, rulesDirectory } = options;
+
+        return {
+            configuration: configuration || DEFAULT_CONFIG,
+            formatter: formatter || "json",
```
Comment (JKillian) [inline src/tslint.ts]: let's just have it default to "prose", since that's what the CLI does. The results are still accessible programmatically alongside of the prose description

File: src/tslint.ts [hunk 3]
```diff
@@ -99,13 +98,19 @@ class Linter {
         return rules.some((r) => r.equals(rule));
     }
 
-    private computeFullOptions() {
-        let {configuration, rulesDirectory} = this.options;
-        if (configuration == null) {
-            configuration = DEFAULT_CONFIG;
+    private computeFullOptions(options: ILinterOptionsRaw): ILinterOptions {
+        if (!options || typeof options !== "object") {
```
Comment (JKillian) [inline src/tslint.ts]: I actually liked what you had before where you threw an error if `typeof options !== "object"`. It's clearly a mistake if that happens, so let's throw an error! As far as if `options` is just null, then we can continue using all the defaults below

File: src/tslint.ts [hunk 4]
```diff
@@ -44,11 +44,10 @@ class Linter {
     private source: string;
     private options: ILinterOptions;
 
-    constructor(fileName: string, source: string, options: ILinterOptions) {
+    constructor(fileName: string, source: string, options: ILinterOptionsRaw) {
         this.fileName = fileName;
         this.source = source;
-        this.options = options;
-        this.computeFullOptions();
+        this.options = this.computeFullOptions(options);
```
Comment (JKillian) [inline src/tslint.ts]: I like this! Better to return a new object than mutate

File: src/lint.ts [hunk 5]
```diff
@@ -44,6 +44,13 @@ export interface LintResult {
     output: string;
 }
 
+export interface ILinterOptionsRaw {
```
Comment (JKillian) [inline src/lint.ts]: Mixed feelings about if we really need a new interface here - I'm sort of inclined to just making the properties of `ILinterOptions` optional. What do you think?

**Comment by JKillian** [comment]
Left my thoughts above @JoshuaKGoldberg, feel free to disagree on any of them!

File: src/tslint.ts (hunk 3 above)
Comment (JoshuaKGoldberg) [inline src/tslint.ts]: Agreed. I'll switch this out.

File: src/lint.ts (hunk 5 above)
Comment (JoshuaKGoldberg) [inline src/lint.ts]: There's a TypeScript issue filed somewhere for letting us do something like `ILinterOptions?`, where every field in `ILinterOptions` would be marked optional (so exactly this).

My problem with re-using one interface for this is that after this initial parsing, the fields *aren't* optional. The semantic intent changes from input option settings to stored options data.

File: src/tslint.ts (hunk 2 above)
Comment (JoshuaKGoldberg) [inline src/tslint.ts]: Ok - would you consider it better to hardcode `"prose"` again or move the setting to configuration.ts?

File: src/lint.ts (hunk 5 above)
Comment (JKillian) [inline src/lint.ts]: Makes sense to me, let's keep this then. It shouldn't cause any backwards compat issues for library users as fulfilling the previous `ILinterOptions` interface will still fulfill the `ILinterOptionsRaw` interface. Maybe we should make the `formattersDirectory` field optional on both though, since it really is optional

File: src/tslint.ts (hunk 2 above)
Comment (JKillian) [inline src/tslint.ts]: I'm good with keeping it here, but either way is fine by me

**Comment by JKillian** [comment]
Beautiful! This turn out very nice
