### PR TITLE
Fix semicolon: Cannot read property 'initializer' of undefined

### LINKED ISSUE #4309: semicolon: Cannot read property 'initializer' of undefined
### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.1.6
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
const
```

with `tslint.json` configuration:

```json
{ "rules": { "semicolon": [true, "never"] } }
```

#### Actual behavior

```
The 'semicolon' rule threw an error in 'test.ts':
TypeError: Cannot read property 'initializer' of undefined
    at SemicolonNeverWalker.checkVariableStatement (...\tslint\lib\rules\semicolonRule.js:309:51)
    ...
```

#### Expected behavior

No error. The code should handle the case where `declarations` is an empty array.

### PR DESCRIPTION
**Pull request by rrogowski**
#### PR checklist

- [x] Addresses an existing issue: #4309 
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [ ] Documentation update

#### Overview of change:

`SemicolonNeverWalker.checkVariableStatement` handles the case where `declarations` is an empty array.

#### Is there anything you'd like reviewers to focus on?

1. Is there any documentation that needs to be updated as a result of this change?
2. Unsure if better to export one of the existing utility functions:
  - `last` (`memberOrderingRule.ts`)
  - `arrayLast` (`switchFinalBreakRule.ts`).

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @rrogowski! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: src/rules/semicolonRule.ts [hunk 1]
```diff
@@ -357,8 +357,8 @@ class SemicolonNeverWalker extends SemicolonWalker {
     }
 
     private checkVariableStatement(node: ts.VariableStatement) {
-        const declarations = node.declarationList.declarations;
-        if (declarations[declarations.length - 1].initializer === undefined) {
+        const declaration = last(node.declarationList.declarations);
+        if (declaration === undefined || declaration.initializer === undefined) {
```
Comment (JoshuaKGoldberg) [inline src/rules/semicolonRule.ts]: Declaring a new `last<T>` is a bit of overhead for this. How about:

```typescript
if (declarations.length !== 0 && declarations[declarations.length - 1].initializer === undefined)
```

File: test/rules/semicolon/never/test.ts.lint [hunk 2]
```diff
@@ -269,4 +269,7 @@ var foo = () => {};
 var bar; var foo = function() {};
 []
 
+const
```
Comment (JoshuaKGoldberg) [inline test/rules/semicolon/never/test.ts.lint]: Let's also check `var` and `let` on their own.

File: src/rules/semicolonRule.ts (hunk 1 above)
Comment (JoshuaKGoldberg) [reply src/rules/semicolonRule.ts]: 🙂 not particularly. [`tslint.json`](https://github.com/palantir/tslint/blob/master/tslint.json) has it set to 140 characters, so this shouldn't trigger it.

**Comment by JoshuaKGoldberg** [comment]
Looks great, thanks @rrogowski! Congrats on the first contribution here! 🎉
