### PR TITLE
[bugfix] `no-unsafe-any`: allow implicitly downcasting `any` to `unknown`

### LINKED ISSUE #4164: no-unsafe-any and `unknown`
Another `unknown` one:

### Bug Report

- __TSLint version__: 5.11.0
- __TypeScript version__: 3.0.3
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
const json = '{ "property": "value" }';
const result: unknown = JSON.parse(json);
```

with `tslint.json` configuration:

```json
{
  "extends": [
    "tslint:recommended"
  ],
  "jsRules": {},
  "rules": {
    "no-unsafe-any": true
  }
}
```

#### Actual behavior
The lint triggers: `Unsafe use of expression of type 'any'.`

#### Expected behavior
Since every type is assignable to `unknown`, the usage is not actually unsafe. The lint shouldn't trigger.

### PR DESCRIPTION
**Pull request by ThomasdenH**
#### PR checklist

- [x] Addresses an existing issue: Closes #4164 
- [x] New feature, bugfix, or enhancement
  - [x] Includes tests
- [x] Documentation update

#### Overview of change:
Downcasting `any` to `unknown` is always safe. This PR fixes the `no-unsafe-any` rule to reflect this.

#### Is there anything you'd like reviewers to focus on?
I have copied from existing test cases and modified them to use `unknown`. I have tried to be exhaustive, but there might still be false positives.

#### CHANGELOG.md entry:
[bugfix] `no-unsafe-any`: allow implicitly downcasting `any` to `unknown`

### CODE REVIEW

**Comment by ThomasdenH** [comment]
It looks like simply ignoring the errors doesn't work here, unfortunately.

**Comment by ThomasdenH** [comment]
Moving the tests containing `unknown` to file that only runs on typescript `>= 3.0.0` fixed it.

File: src/rules/noUnsafeAnyRule.ts [hunk 1]
```diff
@@ -416,22 +416,32 @@ class NoUnsafeAnyWalker extends Lint.AbstractWalker<void> {
 }
 
 /** Check if property has no type annotation in this class and the base class */
-function isPropertyAny(node: ts.PropertyDeclaration, checker: ts.TypeChecker) {
-    if (!isNodeAny(node.name, checker) || node.name.kind === ts.SyntaxKind.ComputedPropertyName) {
+function isPropertyAny(
+    node: ts.PropertyDeclaration,
+    checker: ts.TypeChecker,
+    orUnknown: boolean = false,
```
Comment (JoshuaKGoldberg) [inline src/rules/noUnsafeAnyRule.ts]: `isPropertyAny` is only ever called once. You can remove the `orUnknown` parameter here and replace it with `true`.

**Comment by ThomasdenH** [comment]
The issue has been adressed, this PR is ready for a review when you have the time.

File: test/rules/no-unsafe-any/unknown/test.ts.lint [hunk 2]
```diff
@@ -0,0 +1,82 @@
+[typescript]: >= 3.0.0
+
+import importEquals = require("./commonjsModule");
+import importAlias = importEquals;
+namespace N { export const x: any = 0; }
+import importQualifiedName = N.x;
+import * as namespaceImport from "./es6Module";
+
+declare function takesUnknown(a: any, ...bs: any[]): void;
+takesUnknown(x, x);
```
Comment (adidahiya) [inline test/rules/no-unsafe-any/unknown/test.ts.lint]: don't you need to declare `x` in this scope? what is the inferred type of `x` here?

File: test/rules/no-unsafe-any/unknown/test.ts.lint [hunk 3]
```diff
@@ -0,0 +1,82 @@
+[typescript]: >= 3.0.0
+
+import importEquals = require("./commonjsModule");
+import importAlias = importEquals;
+namespace N { export const x: any = 0; }
+import importQualifiedName = N.x;
+import * as namespaceImport from "./es6Module";
+
```
Comment (adidahiya) [inline test/rules/no-unsafe-any/unknown/test.ts.lint]: I suggest adding here: `declare const x: unknown;`

File: test/rules/no-unsafe-any/unknown/test.ts.lint [hunk 4]
```diff
@@ -0,0 +1,82 @@
...
+function hasThisParameter(this: any) {
+    const u: unknown = this;
+}
+
+(async function(): Promise<unknown> {
+    return x;
+});
+
+const obj = { property: "value" } as any;
+const result: unknown = json;
```
Comment (adidahiya) [inline test/rules/no-unsafe-any/unknown/test.ts.lint]: I suggest making it valid syntax: `const result: unknown = JSON.parse("{}");`

File: test/rules/no-unsafe-any/unknown/test.ts.lint [hunk 5]
```diff
@@ -0,0 +1,82 @@
...
+
+function acceptsUnknown(a: unknown, b: unknown = x) { }
+
+acceptsUnknown(obj);
+
+interface ContainsUnknownProperty {
+    e: unknown;
+}
+
+const p: ContainsUnknownProperty = { e };
```
Comment (adidahiya) [inline test/rules/no-unsafe-any/unknown/test.ts.lint]: also suggest fixing the syntax: ` const p: ContainsUnknownProperty = { e: 123 };`

File: test/rules/no-unsafe-any/unknown/test.ts.lint [hunk 6]
```diff
@@ -0,0 +1,82 @@
...
+
+function f() {
```
Comment (adidahiya) [inline test/rules/no-unsafe-any/unknown/test.ts.lint]: `f` is already a function, let's call this `g`

**Comment by ThomasdenH** [comment]
Thanks for the review! I have adressed your suggestions. I also removed the module imports as they didn't test anything that isn't tested by the other tests for this lint already.
