### PR TITLE
fix(noUnusedVariableRule): remove warning

### LINKED ISSUE #3219: Warning Displayed For Supported `no-unused-variable` Rule
### Bug Report

- __TSLint version__:

```
$ $(yarn bin)/tslint --version
5.7.0
```

- __TypeScript version__:

```
$ $(yarn bin)/tsc --version
Version 2.5.2
```

- __Running TSLint via__: CLI

#### Actual behavior

I'm running `tslint` over an existing code base.

My project has the `no-unused-variable` rule set (through the use of a preset-like package).

My project also has the `noUnusedLocals` and `noUnusedParameters` compiler options enabled for TypeScript (against, through the use of a preset-like package).

I occasionally update my rules and run `tslint`'s `--fix` option to auto-fix my code.

That includes benefiting from the auto-fix feature of the `no-unused-variable` rule.

Example output when running `tslint --fix` on my code base:

```bash
$ $(yarn bin)/tslint --project tsconfig.json --config tslint.json --fix src/**/*.ts
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
WARNING: 'no-unused-variable' lint rule does not need to be set if the 'no-unused-locals' and 'no-unused-parameters' compiler options are enabled.
```

#### Expected behavior

As noted [here](https://github.com/palantir/tslint/issues/1481#issuecomment-282778416) the `no-unused-variable` rule was un-deprecated because users (including myself) benefit from the auto-fix feature.

However the warning implies that I shouldn't be using the rule at all, and causes a lot of unnecessary output to the console, which may obscure other important information such as un-fixable problems in the code.

I believe it would be alright removing the warning.

### PR DESCRIPTION
**Pull request by destroyerofbuilds**
Remove warning printed to console when a user of `tslint` is using the
`no-unused-variable` rule while also using the TypeScript compiler
with the `noUnusedLocals` and `noUnusedParameters` options set.

While it's not technically necessary to use the `noUnusedVariableRule`
rule with the TypeScript compiler options set, using this rule
is still useful when using the `--fix` option in `tslint` to
automatically remove unused variables.

Fixes #3219

### CODE REVIEW

**Comment by palantirtech** [comment]
Thanks for your interest in [palantir/tslint](https://github.com/palantir/tslint), @destroyerofbuilds! Before we can accept your pull request, you need to sign our contributor license agreement - just visit https://cla.palantir.com/ and follow the instructions. Once you sign, I'll automatically update this pull request.

File: src/rules/noUnusedVariableRule.ts [hunk 1]
```diff
@@ -30,6 +30,10 @@ export class Rule extends Lint.Rules.TypedRule {
         description: Lint.Utils.dedent`Disallows unused imports, variables, functions and
             private class members. Similar to tsc's --noUnusedParameters and --noUnusedLocals
             options, but does not interrupt code compilation.`,
+        descriptionDetails: Lint.Utils.dedent`If addition to avoiding compilation errors,
```
Comment (adidahiya) [inline src/rules/noUnusedVariableRule.ts]: "In addition ..."

Comment (adidahiya) [reply src/rules/noUnusedVariableRule.ts]: Also you can add a newline + indentation before "If"

File: src/rules/noUnusedVariableRule.ts [hunk 2]
```diff
@@ -30,6 +30,10 @@ export class Rule extends Lint.Rules.TypedRule {
...
+            this rule may still be useful if you wish to have \`tslint\` automatically
+            remove unused imports, variables, functions, and private class members, when
+            using \`tslint\`'s \`--fix\` option.`,
```
Comment (adidahiya) [inline src/rules/noUnusedVariableRule.ts]: "... TSLint's \`--fix\` option."

File: src/rules/noUnusedVariableRule.ts (hunk 1 above)
Comment (destroyerofbuilds) [reply src/rules/noUnusedVariableRule.ts]: Fixed `if`, and moved the start of the sentence to a newline.

File: src/rules/noUnusedVariableRule.ts (hunk 2 above)
Comment (destroyerofbuilds) [reply src/rules/noUnusedVariableRule.ts]: Fixed TSLint name.

**Comment by destroyerofbuilds** [comment]
I'm waiting on approval to sign the CLA.

In the meantime, please keep in mind that (And that I am not a lawyer): Many of the provisions of the Palantir CLA are covered by the Apache license itself.

Please see the _Lowering the Barriers to Participation_ section of https://blog.openshift.com/keep-calm-and-merge-on-lowering-barriers-to-open-source-contributions-with-apache-v2/.

**Comment by destroyerofbuilds** [comment]
I've been approved to sign the CLA.

I'm not sure why my modification has caused several of the tests to fail. The output messages aren't even related to this change.

Is there anything I can do to correct the issue?

**Comment by ajafff** [comment]
The CI failures are not related to your changes.
That's already fixed on master, so you just need to merge

**Comment by adidahiya** [comment]
CI should be fixed when this lands on master.

**Comment by adidahiya** [comment]
thanks @destroyerofbuilds!

**Comment by jensbodal** [comment]
Really look forward to this in the next release -- thank you

We set rules like `noUnusedParameters: true` in our `tsconfig.json`, but then disable them in our `tsconfig.app.json`. This allows `tslint-language-service` to provide as-you-type warnings for unused parameters.  Our pre-commit hooks run linting with type-checking enabled to fail commits that don't pass `no-unused-variable`.  And the our builds work with 3rd party libraries that don't enforce things like `noUnusedParameters` or `noImplicitAny`.
