### PR TITLE
4660-[import-blacklist]: Added examples and fix optionsDescription

### LINKED ISSUE #4660: [Question] Import-blacklist by regex does not work as expected
### Question

- __TSLint version__: 5.15.0
- __TypeScript version__: 3.4.3
- __Running TSLint via__: CLI / VSCode 

#### TypeScript code being linted

```ts
import { SecondaryService } from "./src";
export class BasicService {
    public State: boolean;

    constructor(public s: SecondaryService) {

    }
}
```

with `tslint.json` configuration:

```
{
    "defaultSeverity": "error",
    "extends": [
        "tslint:recommended"
    ],
    "jsRules": {},
    "rules": {
        "import-blacklist": [
            true,
            "^.*src$",
        ]
    },
    "rulesDirectory": []
}
```

#### Actual behavior
Tslint does not emit any errors

#### Expected behavior
string `import { SecondaryService } from "./src";` should mark as wrong by import-blacklist regex rule

#### Mini-repo
https://github.com/alxpsr/tslint-regex

#### Questions
- What im doing wrong? 
- How can i disallow importing from `import-blacklist` regex patterns?

### PR DESCRIPTION
**Pull request by tanmoyopenroot**
#### PR checklist

- [x] Addresses an existing issue: fixes #4660 
- [ ] New feature, bugfix, or enhancement
- [ ] Includes tests
- [x] Documentation update

#### Overview of change:
Added examples in `optionExamples` and change `optionsDescription` to specify the requirement of an array of regular expression

### CODE REVIEW

File: src/rules/importBlacklistRule.ts [hunk 1]
```diff
@@ -41,7 +41,7 @@ export class Rule extends Lint.Rules.AbstractRule {
             In other cases, you may simply want to ban an import because using
             it is undesirable or unsafe.`,
         optionsDescription:
-            "A list of blacklisted modules, named imports, or regular expression patterns.",
+            "A list of blacklisted modules, named imports, or an array of expression patterns.",
```
Comment (adidahiya) [inline src/rules/importBlacklistRule.ts]: I think we should keep the word "regular" in there; it should say "... regular expression ..."

Comment (tanmoyopenroot) [reply src/rules/importBlacklistRule.ts]: Done
