### PR TITLE
Fix false positive in `prefer-for-of` when array is in parentheses

### LINKED ISSUE #1931: prefer-for-of rule false positive
### Bug Report

- __TSLint version__: `4.2.0`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: (please choose one) CLI

#### TypeScript code being linted

```ts
const a = [1, 2];
const b = [2, 3];
for (let i = 0; i < a.length; i++) {
    console.log(a[i] + b[i]);
}
```

with `tslint.json` configuration:

```json
{
    "extends": "tslint:latest",
    "rules": {
        "forin": false,
        "interface-name": [
            false
        ],
        "max-line-length": [
            false
        ],
        "no-var-requires": false,
        "no-console": [
            false
        ],
        "no-string-literal": false,
        "no-reference": false,
        "ordered-imports": [
            false
        ],
        "object-literal-sort-keys": false,
        "variable-name": [
            true,
            "ban-keywords"
        ],
        "no-bitwise": false,
        "member-access": false,
        "arrow-parens": false,
        "array-type": [true, "array"],
        "max-classes-per-file": [false]
    }
}
```

#### Actual behavior

Expected a 'for-of' loop instead of a 'for' loop with this simple iteration

#### Expected behavior

No error.
Because the code cannot be transformed to for...of.

### PR DESCRIPTION
**Pull request by nchen63**
fixes #1931

### CODE REVIEW

File: src/rules/preferForOfRule.ts [hunk 1]
```diff
@@ -17,7 +17,7 @@
 
 import * as ts from "typescript";
 import * as Lint from "../index";
-import { isAssignment } from "../language/utils";
+import { isAssignment, unwrapParentheses } from "../language/utils";
```
Comment (ajafff) [inline src/rules/preferForOfRule.ts]: don't know if this is a requirement, but all other rules use the functions from the `Lint` namespace. for consistency you could use `Lint.isAssignment` and `Lint.unwrapParentheses` here

Comment (adidahiya) [inline src/rules/preferForOfRule.ts]: Good point, but that was mainly done for expediency when transitioning the codebase from namespaces to modules -- it was easiest to reference things on the `Lint` object. Now that we have modules, it would be nice to slowly move to more granular imports.
