### PR TITLE
adjacent-overload-signatures: Convert to function

### LINKED ISSUE #2482: adjacent-overload-signatures incorrect with one-liners
### Bug Report

- __TSLint version__: 5.0.0
- __TypeScript version__: 2.3.0-dev.20170329
- __Running TSLint via__: (pick one) CLI and VSCode

#### TypeScript code being linted

```ts
class Testclass {
	private _test: number;
	set test(v: number) { this._test = v; };
	get test(): number { return this._test; };
}
```

with `tslint.json` configuration:

```json
{
    "extends": "tslint:latest",
    "rules": {}
}
```

#### Actual behavior
ERROR: test.ts[6, 2]: All 'test' signatures should be adjacent
#### Expected behavior
No error.

I suppose it could rather be an error with getters and setters depending on how it should behave.

### PR DESCRIPTION
**Pull request by andy-hanson**
#### PR checklist

- [X] Addresses an existing issue: #2482
- [ ] New feature, bugfix, or enhancement
  - [ ] Includes tests
- [ ] Documentation update

#### Overview of change:

Just a refactor.

**EDIT**: Now also fixes #2482.
[bugfix] `adjacent-overload-signatures` handles functions ending in semicolon

### CODE REVIEW

File: src/rules/adjacentOverloadSignaturesRule.ts [hunk 1]
```diff
@@ -35,128 +34,107 @@ export class Rule extends Lint.Rules.AbstractRule {
...
-    public visitModuleDeclaration(node: ts.ModuleDeclaration) {
-        const { body } = node;
-        if (body && body.kind === ts.SyntaxKind.ModuleBlock) {
-            this.visitStatements((body as ts.ModuleBlock).statements);
+function walk(ctx: Lint.WalkContext<void>): void {
+    const { sourceFile } = ctx;
+    visitStatements(sourceFile.statements);
+    return ts.forEachChild(sourceFile, function cb(node: ts.Node): void {
+        switch (node.kind) {
+            case ts.SyntaxKind.ModuleBlock:
```
Comment (ajafff) [inline src/rules/adjacentOverloadSignaturesRule.ts]: add a case for `ts.SyntaxKind.Block`?

Comment (andy-hanson) [inline src/rules/adjacentOverloadSignaturesRule.ts]: TypeScript won't allow non-adjacent overloads in a regular block anyway.
