### PR TITLE
ordered-imports: check that all imports of the same type are groupped

### LINKED ISSUE #3727: ordered-imports not failing when there is a blank line
### Bug Report

- __TSLint version__: 5.9.1
- __TypeScript version__: 2.7.2

#### TypeScript code being linted

```ts
import { CommonModule } from "@angular/common";
import { NgModule } from "@angular/core";

import { IonicModule } from "ionic-angular";

import { SkeletonComponent } from "./skeleton/skeleton.component";
```

with `tslint.json` configuration:

```json
"ordered-imports": [
	true,
	{
		"grouped-imports": true
	}
],
```

#### Actual behavior
No error

#### Expected behavior
I expected that that there is an error that imports are not group. In fact if I run the linter with fixer (If i have an error in the imports) it will remove the extra blank line.

### LINKED ISSUE #3873: New rule: grouping imports by type of imported entity
In our projects we trying to keep imports clean as possible and we grouping imports by type of imported entity:

* imports from node modules (all things)
* imports from types
* imports from interfaces
* imports from enums
* other imports (classes, functions, constants)

```
import * as escodegen from 'escodegen-wallaby';
import * as espree from 'espree';
import * as ESTree from 'estree';

import { TObject } from './types/TObject';

import { IGeneratorOutput } from './interfaces/IGeneratorOutput';
import { IJavaScriptObfuscator } from './interfaces/IJavaScriptObfsucator';
import { ILogger } from './interfaces/logger/ILogger';
import { IObfuscationResult } from './interfaces/IObfuscationResult';
import { IOptions } from './interfaces/options/IOptions';
import { IRandomGenerator } from './interfaces/utils/IRandomGenerator';
import { ISourceMapCorrector } from './interfaces/source-map/ISourceMapCorrector';
import { ITransformersRunner } from './interfaces/node-transformers/ITransformersRunner';

import { LoggingMessage } from './enums/logger/LoggingMessage';
import { NodeTransformer } from './enums/node-transformers/NodeTransformer';
import { TransformationStage } from './enums/node-transformers/TransformationStage';

import { EspreeFacade } from './EspreeFacade';
import { NodeGuards } from './node/NodeGuards';
```

It will nice to have rule that will check that grouping by type of imported entity.
If few things are imported from the module - import should be attached to the group by most prevailing type of imported entity:

```ts
import {TFoo, TBar, IFoo} from '../../foo'; <- add to types group
```

### PR DESCRIPTION
**Pull request by no23reason**
#### PR checklist

- [x] Addresses an existing issue: #3727
- [x] Enhancement
  - [x] Includes tests
- [x] Documentation update (not needed as the change conforms to the current docs)

#### Overview of change:

As stated in #3727 when enforcing grouping we should also enforce there is at most one group of imports of the same type in the file. 

#### CHANGELOG.md entry:

[enhancement] When `grouped-imports` option of the `ordered-imports` rule is set, the fact that imports of the same type are all in one group is also checked.

### CODE REVIEW

**Comment by no23reason** [comment]
@adidahiya pinging you if we could please re-run the circleci build? I believe the failing build has nothing to do with my changes.

**Comment by alan-agius4** [comment]
Lets get this merged please!

File: src/rules/orderedImportsRule.ts [hunk 1]
```diff
@@ -116,6 +116,7 @@ export class Rule extends Lint.Rules.AbstractRule {
         "Import sources of different groups must be sorted by: libraries, parent directories, current directory.";
     public static IMPORT_SOURCES_UNORDERED = "Import sources within a group must be alphabetized.";
     public static NAMED_IMPORTS_UNORDERED = "Named imports must be alphabetized.";
+    public static IMPORT_SOURCES_OF_SAME_TYPE_NOT_IN_ONE_GROUP = "Import sources of the same type must be grouped together.";
```
Comment (giladgray) [inline src/rules/orderedImportsRule.ts]: the word `type` here confused the heck out of me! you want to group my `string` imports separately from `functions`??

then i figured out what you mean. is there a word other than `type` we can use to describe this? perhaps `source`?

Comment (giladgray) [reply src/rules/orderedImportsRule.ts]: build will pass after you push a fix for this language :)

Comment (no23reason) [reply src/rules/orderedImportsRule.ts]: @giladgray Thank you for the review. I agree the word `type` is to general, however "Import sources of the same source..." sounds even weirder imo :/ I took the term `Import source` from the existing error message two lines up.

I decided to add an explanation to the error message. Do you think it is clearer now?

**Comment by giladgray** [comment]
@no23reason could you merge latest `master` to see if we can resolve this build failure?

**Comment by no23reason** [comment]
@giladgray It seems to bee failing at some other rule (`no-unused-variable`). The merge itself went OK.

**Comment by no23reason** [comment]
@giladgray I rebased my branch onto the current master and the `testNext` build still fails on `no-unused-variable`. What can I do to make this pass?

**Comment by suchanlee** [comment]
@no23reason https://github.com/palantir/tslint/pull/3958 should have addressed the build issue that you're seeing and rebasing off of that should do the trick. TS2.9 nightlies and the `no-unused-variables` haven't been going well together

**Comment by no23reason** [comment]
@suchanlee thank you, it finally builds 😌

**Comment by no23reason** [comment]
@giladgray Pinging you as it finally builds, maybe we can merge this now :)

**Comment by no23reason** [comment]
It has been several months since I opened this PR. Is there anything I can do to help to get it merged?

**Comment by ericanderson** [comment]
Sorry for the delay.
