### PR TITLE
Fix restrict-plus-operands for ternary ops

### LINKED ISSUE #1922: restrict-plus-operands false positive with ternary operator
### Bug Report

- __TSLint version__: `4.2.0`
- __TypeScript version__: `2.1.4`
- __Running TSLint via__: CLI

#### TypeScript code being linted

```ts
const balls = 'hello' + (someBoolean ? 'a' : 'b') + (() => someBoolean ? 'c' : 'd')() + 'e';
```

with `tslint.json` configuration:

```json
{
	"rules": {
		"restrict-plus-operands": true
	}
}
```

#### Actual behavior

`Operands of '+' operation must either be both strings or both numbers`

#### Expected behavior

No error, as with TS 2.0.10 and tslint 4.1.1.

### PR DESCRIPTION
**Pull request by nchen63**
fixes #1922

### CODE REVIEW

File: src/rules/restrictPlusOperandsRule.ts [hunk 1]
```diff
@@ -40,6 +41,8 @@ export class Rule extends Lint.Rules.TypedRule {
     }
 }
 
+type AddTypes = "string" | "number" | "invalid";
```
Comment (adidahiya) [inline src/rules/restrictPlusOperandsRule.ts]: I don't think we need a new type for this; I would prefer the union inlined in two places. This change makes the code more confusing

File: src/rules/restrictPlusOperandsRule.ts [hunk 2]
```diff
@@ -60,12 +63,34 @@ class RestrictPlusOperandsWalker extends Lint.ProgramAwareRuleWalker {
     }
 }
 
-function getAddableType(node: ts.Expression, tc: ts.TypeChecker): "string" | "number" | "invalid" {
+function getAddableType(node: ts.Expression, tc: ts.TypeChecker): AddTypes {
```
Comment (adidahiya) [inline src/rules/restrictPlusOperandsRule.ts]: I don't think this extra function in the call stack is necessary -- would prefer to inline usage of `getBaseTypeOfLiteralType` above, like so:

```ts
const tc = this.getTypeChecker();
const leftType = getBaseTypeOfLiteralType(ts.getTypeAtLocation(node.left));
...
```

File: src/rules/restrictPlusOperandsRule.ts [hunk 3]
```diff
@@ -60,12 +63,34 @@ class RestrictPlusOperandsWalker extends Lint.ProgramAwareRuleWalker {
...
+    } else if (isTypeFlagSet(type, ts.TypeFlags.Union) && !isTypeFlagSet(type, ts.TypeFlags.Enum)) {
+        const types = (type as ts.UnionType).types.map(getBaseTypeOfLiteralType);
+        return allSame(types) ? types[0] : "invalid";
+    } else if (isTypeFlagSet(type, ts.TypeFlags.EnumLiteral)) {
+        return getBaseTypeOfLiteralType((type as ts.EnumLiteralType).baseType);
     }
     return "invalid";
 }
+
+function allSame(array: string[]) {
```
Comment (adidahiya) [inline src/rules/restrictPlusOperandsRule.ts]: I think this would be nicer with `Array#reduce`
