### PR TITLE
Fix bug where await expressions were marked as unused

### LINKED ISSUE #887: `no-unused-expression` should permit `await`
The following code causes a linter error:

	async function f(foo: Promise<void>): Promise<number> {
		await foo
		return 0
	}

The output I get is:

	src/foo.ts[2, 2]: expected an assignment or function call

Here's my `tslint.json`:

	{
		"rules": {
			"no-unused-expression": true
		}
	}

### PR DESCRIPTION
**Pull request by JKillian**
Fixes #887

### CODE REVIEW

File: src/rules/noUnusedExpressionRule.ts [hunk 1]
```diff
@@ -38,17 +38,17 @@ class NoUnusedExpressionWalker extends Lint.RuleWalker {
...
-                const expressionText = node.expression.getText();
-                if (expressionText === "\"use strict\"" || expressionText === "'use strict'") {
-                    return;
-                }
-            } else if (node.expression.kind === ts.SyntaxKind.DeleteExpression || node.expression.kind === ts.SyntaxKind.YieldExpression) {
-                return;
-            }
+            const { expression } = node;
+            const { kind } = expression;
+            const isValidStandAloneExpressionKind = kind === ts.SyntaxKind.DeleteExpression
```
Comment (adidahiya) [inline src/rules/noUnusedExpressionRule.ts]: nit: "standalone" is one word, not 2, and I think `Kind` is useless in this identifier

i.e. `isValidStandaloneExpression`

**Comment by adidahiya** [comment]
feel free to merge after small rename :+1:

File: src/rules/noUnusedExpressionRule.ts (hunk 1 above)
Comment (JKillian) [inline src/rules/noUnusedExpressionRule.ts]: Haha good call, meant to look that one up actually
